// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAblJa8nEWaSUgMZYncU1PGZYb6VtDzZOE",
      authDomain: "instagram-clone-flutter-11473.firebaseapp.com",
      projectId: "instagram-clone-flutter-11473",
      storageBucket: "instagram-clone-flutter-11473.appspot.com",
      messagingSenderId: "935465107849",
      appId: "1:935465107849:web:8053c811b8a110ffe42158");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5TGo187GroFhxPTKb-7JNNuoh_R6uuIg',
    appId: '1:935465107849:android:542b71aeaafc15dee42158',
    messagingSenderId: '935465107849',
    projectId: 'instagram-clone-flutter-11473',
    storageBucket: 'instagram-clone-flutter-11473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5is5yHYbjd-zL7f5jutRmDfDKPqawoM',
    appId: '1:935465107849:ios:245da64dbd9965c4e42158',
    messagingSenderId: '935465107849',
    projectId: 'instagram-clone-flutter-11473',
    storageBucket: 'instagram-clone-flutter-11473.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5is5yHYbjd-zL7f5jutRmDfDKPqawoM',
    appId: '1:935465107849:ios:ebf04f2845564c6ee42158',
    messagingSenderId: '935465107849',
    projectId: 'instagram-clone-flutter-11473',
    storageBucket: 'instagram-clone-flutter-11473.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
